### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by haesleinhuepf** [ksugar/czi_sampling#1]
Hi @ksugar ,

nice repository! Great that you are sharing it open source! I was just wondering under which conditions one could reuse the code and materials provided here. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by ksugar** [comment]
Hi @haesleinhuepf,

Thank you for your kind words and for highlighting this important aspect! I totally agree that having a clear license is crucial for open-source projects. I have now added a license file to the repository. https://github.com/ksugar/czi_sampling/commit/22f39f30d1efdcc9dedff5590d023260881aca37
By the way, the blog post you shared is great—really insightful and a good reminder of why licensing our work properly is so important.
Your feedback is greatly appreciated!

Best,
Ko
